import { docTypeLabel } from '@/lib/constants/doc-types';
import { toIsoDate } from '@/lib/text/dates';
import type { RecordDetail } from '@/types/record';

import { CONTACT_EMAIL, SITE_NAME, SITE_URL, SOURCE_NAME, absoluteUrl } from './config';

/** Spec 8.3 — schema selection by page type. */

export function websiteJsonLd() {
  return {
    '@context': 'https://schema.org',
    '@type': 'WebSite',
    name: SITE_NAME,
    url: SITE_URL,
    inLanguage: 'tr',
    potentialAction: {
      '@type': 'SearchAction',
      target: {
        '@type': 'EntryPoint',
        urlTemplate: SITE_URL + '/ara?q={search_term_string}',
      },
      'query-input': 'required name=search_term_string',
    },
  };
}

/**
 * The publisher identity — spec 8.3.
 *
 * The site emitted a `WebSite` node and, inside the record schemas, `publisher`
 * objects carrying a bare name and url. Nothing tied those together into an entity
 * with a logo, which is what a search engine needs before it can attach a brand to
 * the domain. This node is that missing anchor; `@id` gives the record schemas
 * something stable to point at rather than repeating an anonymous object.
 *
 * `logo` is a PNG generated by app/logo.png/route.tsx — see the note there for why
 * it is not the SVG icon.
 */
export function organizationJsonLd() {
  return {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    '@id': SITE_URL + '/#organization',
    name: SITE_NAME,
    url: SITE_URL,
    logo: {
      '@type': 'ImageObject',
      url: absoluteUrl('/logo.png'),
      width: 512,
      height: 512,
    },
    /*
     * Said plainly in the structured data too, not only in the footer: this is an
     * independent archive, not a government body. Everything else on the site is
     * careful about that claim (spec 8.4) and the machine-readable layer should not
     * be the one place it goes unsaid.
     */
    description:
      SITE_NAME +
      ', KKTC Resmî Gazete kayıtlarını aranabilir hâle getiren bağımsız bir arşivdir. Resmî bir kurum değildir.',
    inLanguage: 'tr',
    email: CONTACT_EMAIL,
  };
}

export function breadcrumbJsonLd(items: Array<{ name: string; href?: string }>) {
  return {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: items.map((item, index) => ({
      '@type': 'ListItem',
      position: index + 1,
      name: item.name,
      ...(item.href ? { item: absoluteUrl(item.href) } : {}),
    })),
  };
}

const LEGISLATION_TYPES = new Set([
  'yasa',
  'yasa_gucunde_kararname',
  'tuzuk',
  'emirname',
  'yasa_tasarisi',
  'yasa_onerisi',
]);

const JOB_TYPES = new Set(['munhal_ilani']);

/**
 * The record page schema. There are three paths, and the choice follows the data
 * rather than the page:
 *
 *   legislation -> Legislation
 *   vacancy     -> JobPosting, ONLY if deadline_at is filled in
 *   otherwise   -> Article
 *
 * JobPosting's `validThrough` field is mandatory. Emitted with an empty
 * `deadline_at` it produces Search Console errors and puts the whole page type at
 * risk (spec 8.3), so those records fall back to Article.
 */
export function recordJsonLd(record: RecordDetail) {
  const url = absoluteUrl('/karar/' + record.slug);
  const name = record.summary ?? record.title;
  const datePublished = toIsoDate(record.publishedAt);
  const institution = record.entities.find((entity) => entity.kind === 'institution');

  const publisher = {
    '@type': 'Organization',
    name: SITE_NAME,
    url: SITE_URL,
  };

  if (JOB_TYPES.has(record.docType) && record.deadlineAt) {
    return {
      '@context': 'https://schema.org',
      '@type': 'JobPosting',
      title: name,
      description: record.bodyText ?? record.title,
      datePosted: datePublished,
      validThrough: toIsoDate(record.deadlineAt),
      employmentType: 'FULL_TIME',
      hiringOrganization: {
        '@type': 'GovernmentOrganization',
        name: institution?.name ?? 'Kuzey Kıbrıs Türk Cumhuriyeti',
        ...(institution ? { url: absoluteUrl('/kurum/' + institution.slug) } : {}),
      },
      jobLocation: {
        '@type': 'Place',
        address: {
          '@type': 'PostalAddress',
          addressCountry: 'CY',
          addressRegion: 'Kuzey Kıbrıs',
        },
      },
      url,
      isBasedOn: record.issue.pdfUrl,
    };
  }

  if (LEGISLATION_TYPES.has(record.docType)) {
    return {
      '@context': 'https://schema.org',
      '@type': 'Legislation',
      name,
      alternateName: record.title,
      legislationIdentifier: record.refNumber ?? undefined,
      legislationDate: datePublished,
      legislationType: docTypeLabel(record.docType),
      jurisdiction: {
        '@type': 'AdministrativeArea',
        name: 'Kuzey Kıbrıs Türk Cumhuriyeti',
      },
      inLanguage: 'tr',
      url,
      isBasedOn: record.issue.pdfUrl,
      publisher,
    };
  }

  return {
    '@context': 'https://schema.org',
    '@type': 'Article',
    headline: name,
    alternativeHeadline: record.title,
    datePublished,
    inLanguage: 'tr',
    url,
    isBasedOn: record.issue.pdfUrl,
    publisher,
    isPartOf: {
      '@type': 'PublicationIssue',
      issueNumber: record.issue.number,
      datePublished: toIsoDate(record.issue.publishedAt),
      name: SOURCE_NAME + ' sayı ' + record.issue.number + '/' + record.issue.year,
    },
  };
}

/** `recordCount` used to be a parameter here and was never read — GovernmentOrganization has no field for it. */
export function institutionJsonLd(entity: { name: string; slug: string }) {
  return {
    '@context': 'https://schema.org',
    '@type': 'GovernmentOrganization',
    name: entity.name,
    url: absoluteUrl('/kurum/' + entity.slug),
    areaServed: { '@type': 'AdministrativeArea', name: 'Kuzey Kıbrıs Türk Cumhuriyeti' },
  };
}

export function faqJsonLd(items: Array<{ question: string; answer: string }>) {
  return {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: items.map((item) => ({
      '@type': 'Question',
      name: item.question,
      acceptedAnswer: { '@type': 'Answer', text: item.answer },
    })),
  };
}
